"""drop_display_name

Revision ID: faae4c20080a
Revises: b03dd0c6bdcf
Create Date: 2026-04-14 00:24:12.697170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faae4c20080a'
down_revision: Union[str, Sequence[str], None] = 'b03dd0c6bdcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
